name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
      with:
        path: 'src/knowrob'
    
    - name: Checkout rosprolog
      uses: actions/checkout@v2
      with:
        path: 'src/rosprolog'
        repository: daniel86/rosprolog
    
    - name: Checkout SOMA ontology
      uses: actions/checkout@v2
      with:
        path: 'src/ease_ontology'
        repository: knowrob/ease_ontology
    
    - name: Checkout DUL ontology
      uses: actions/checkout@v2
      with:
        path: 'src/dul'
        repository: ease-crc/dul
    
    - name: Checkout iai_common_msgs
      uses: actions/checkout@v2
      with:
        path: 'src/iai_common_msgs'
        repository: code-iai/iai_common_msgs
    
    - name: Setup catkin workspace
      uses: janbernloehr/github-setup-catkin@patch-1
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax.
        ros-version: melodic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE
    
    - name: Build catkin workspace
      run: catkin_make_isolated
    
    - name: Run tests
      shell: bash
      run: |
        sudo systemctl start mongod
        roscore &
        source $GITHUB_WORKSPACE/devel_isolated/setup.bash
        rosrun rosprolog rosprolog-test -o junit-knowrob.xml knowrob
      
    - name: Report plunit results as Github Actions Annotations
      uses: daniel86/junit-report-annotations-action@master
      with:
        path: junit-*.xml
        stripFromPath: /home/runner/work/knowrob/knowrob/src/knowrob/
        accessToken: ${{ secrets.GITHUB_TOKEN }}
