name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/knowrob' 
    - name: Checkout rosprolog
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/rosprolog'
        repository: knowrob/rosprolog
    - name: Checkout iai_common_msgs
      uses: actions/checkout@v2
      with:
        path: 'ros_ws/src/iai_common_msgs'
        repository: code-iai/iai_common_msgs
    - name: Setup KnowRob workspace
      uses: betwo/github-setup-catkin@master
      env:
            ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      with:
        # Version range or exact version of ROS version to use, using SemVer's version range syntax. 
        ros-version: noetic
        # Root directory of the catkin workspace
        workspace: $GITHUB_WORKSPACE/ros_ws
    - name: Build KnowRob workspace
      shell: bash
      run: |
        sudo add-apt-repository ppa:swi-prolog/stable
        sudo apt-get update -y -qq
        sudo apt-get install swi-prolog libspdlog-dev
        cd ros_ws
        catkin_make_isolated
    - name: Run KnowRob plunit tests
      shell: bash
      run: |
        sudo systemctl start mongod
        export ROS_HOSTNAME=localhost
        roscore &
        source $GITHUB_WORKSPACE/ros_ws/devel_isolated/setup.bash
        export LD_LIBRARY_PATH="$GITHUB_WORKSPACE/ros_ws/devel_isolated/knowrob/lib/knowrob:$LD_LIBRARY_PATH"
        cd $GITHUB_WORKSPACE/ros_ws/src/knowrob
        $GITHUB_WORKSPACE/ros_ws/devel_isolated/knowrob/lib/knowrob/all_gtests --gtest_filter=* --gtest_output="xml:$GITHUB_WORKSPACE/ros_ws/junit-knowrob.xml" --gtest_color=no || true
        echo "LIB"
        ls $GITHUB_WORKSPACE/ros_ws/devel_isolated/knowrob/lib/knowrob
    - name: Report plunit results as Github Actions Annotations
      uses: daniel86/junit-report-annotations-action@master
      with:
        path: junit-*.xml
        stripFromPath: /home/runner/work/knowrob/knowrob/ros_ws/src/knowrob/
        accessToken: ${{ secrets.GITHUB_TOKEN }}
    #####
    - name: Run pldoc
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        source $GITHUB_WORKSPACE/ros_ws/devel_isolated/setup.bash
        cp $GITHUB_WORKSPACE/ros_ws/src/knowrob/README.md $GITHUB_WORKSPACE/ros_ws/src/knowrob/src/
        rosrun rosprolog rosprolog-doc knowrob
    - name: Move checkout
      run: |
        mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/.git $GITHUB_WORKSPACE/
        mv $GITHUB_WORKSPACE/ros_ws/src/knowrob/* $GITHUB_WORKSPACE/
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploy pldoc to gh-pages
      if: ${{ github.event_name == 'push' }}
      uses: JamesIves/github-pages-deploy-action@3.5.7
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # The branch the action should deploy to.
        BRANCH: gh-pages
        # The folder the action should deploy.
        FOLDER: doc
        # The folder in the target branch
        TARGET_FOLDER: ${{ steps.extract_branch.outputs.branch }}
        CLEAN: true
        SINGLE_COMMIT: true
